version: "2.22"
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - mynetwork
    ports:
      - "27017:27017"

  task_crud_backend:
    container_name: task_crud_backend
    build:
      context: ./node
      dockerfile: Dockerfile.node
    networks:
      - mynetwork
    ports:
      - "9000:9000"
    environment:
      DB_URI: "mongodb://mongodb:27017/bd"
      PORT: "9000"
      REACT_APP_VERSION: "2.0.0"
    depends_on:
      - mongodb

  task_crud_frontend:
    container_name: task_crud_frontend
    build:
      context: ./react
      dockerfile: Dockerfile.react
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BACK: "http://localhost:9000"
      version_app: "1.0.0"
    depends_on:
      - task_crud_backend

  nginx:
    image: nginx:latest
    networks:
      - mynetwork
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - task_crud_backend
      - task_crud_frontend

networks:
  mynetwork:

volumes:
  mongodb_data:
