version: "2.22"
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"

  task-crud-backend:
    container_name: task-crud-backend
    build:
      context: ./node
      dockerfile: Dockerfile.node
    ports:
      - "9000:9000"
    environment:
      DB_URI: "mongodb://mongodb:27017/bd"
      PORT: "9000"
    depends_on:
      - mongodb

  task-crud-frontend:
    container_name: task-crud-frontend
    build:
      context: ./react
      dockerfile: Dockerfile.react
    ports:
      - "80:80"
    environment:
      REACT_APP_API_BACK: "http://localhost:9000"
    depends_on:
      - task-crud-backend
